global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    system: 'messaging-platform'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'api-gateway'

  - job_name: 'messaging-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'messaging-service'

  - job_name: 'persistence-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'persistence-service'

  - job_name: 'delivery-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8083']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'delivery-service'