apiVersion: v1
kind: ConfigMap
metadata:
  name: messaging-config
  namespace: messaging
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/messaging_platform"
  SPRING_DATA_MONGODB_URI: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongodb-service:27017/messaging_messages?authSource=admin"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  SPRING_DATA_REDIS_HOST: "redis-service"
  SPRING_DATA_REDIS_PORT: "6379"

  CPP_PROCESSOR_HOST: "cpp-processor-service"
  CPP_PROCESSOR_PORT: "9090"

  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_STOMP_PORT: "61613"

  JWT_EXPIRATION_MS: "86400000" # 24h